// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpfcollector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpRetransmitFlowKeyIpv4 struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

type tcpRetransmitFlowKeyIpv6 struct {
	_     structs.HostLayout
	Saddr [16]uint8
	Daddr [16]uint8
	Sport uint16
	Dport uint16
}

type tcpRetransmitNetdiagFlowStats struct {
	_           structs.HostLayout
	Retransmits uint64
}

// loadTcpRetransmit returns the embedded CollectionSpec for tcpRetransmit.
func loadTcpRetransmit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpRetransmitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpRetransmit: %w", err)
	}

	return spec, err
}

// loadTcpRetransmitObjects loads tcpRetransmit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpRetransmitObjects
//	*tcpRetransmitPrograms
//	*tcpRetransmitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpRetransmitObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpRetransmit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpRetransmitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpRetransmitSpecs struct {
	tcpRetransmitProgramSpecs
	tcpRetransmitMapSpecs
	tcpRetransmitVariableSpecs
}

// tcpRetransmitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpRetransmitProgramSpecs struct {
	CountTcpRetransmit *ebpf.ProgramSpec `ebpf:"count_tcp_retransmit"`
}

// tcpRetransmitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpRetransmitMapSpecs struct {
	RetransmitCount        *ebpf.MapSpec `ebpf:"retransmit_count"`
	TcpRetransmitFlowsIpv4 *ebpf.MapSpec `ebpf:"tcp_retransmit_flows_ipv4"`
	TcpRetransmitFlowsIpv6 *ebpf.MapSpec `ebpf:"tcp_retransmit_flows_ipv6"`
}

// tcpRetransmitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpRetransmitVariableSpecs struct {
}

// tcpRetransmitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpRetransmitObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpRetransmitObjects struct {
	tcpRetransmitPrograms
	tcpRetransmitMaps
	tcpRetransmitVariables
}

func (o *tcpRetransmitObjects) Close() error {
	return _TcpRetransmitClose(
		&o.tcpRetransmitPrograms,
		&o.tcpRetransmitMaps,
	)
}

// tcpRetransmitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpRetransmitObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpRetransmitMaps struct {
	RetransmitCount        *ebpf.Map `ebpf:"retransmit_count"`
	TcpRetransmitFlowsIpv4 *ebpf.Map `ebpf:"tcp_retransmit_flows_ipv4"`
	TcpRetransmitFlowsIpv6 *ebpf.Map `ebpf:"tcp_retransmit_flows_ipv6"`
}

func (m *tcpRetransmitMaps) Close() error {
	return _TcpRetransmitClose(
		m.RetransmitCount,
		m.TcpRetransmitFlowsIpv4,
		m.TcpRetransmitFlowsIpv6,
	)
}

// tcpRetransmitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpRetransmitObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpRetransmitVariables struct {
}

// tcpRetransmitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpRetransmitObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpRetransmitPrograms struct {
	CountTcpRetransmit *ebpf.Program `ebpf:"count_tcp_retransmit"`
}

func (p *tcpRetransmitPrograms) Close() error {
	return _TcpRetransmitClose(
		p.CountTcpRetransmit,
	)
}

func _TcpRetransmitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpretransmit_bpfeb.o
var _TcpRetransmitBytes []byte
